### PR TITLE
Move from tokio-core to tokio.

### LINKED ISSUE #2: Update to tokio 0.1
Tokio library made reorganization and moved from `tokio-core` to `tokio`, `tokio-reactor` and so on.

Are any plans to upgrade to it?

### PR DESCRIPTION
**Pull request by o01eg**
Fix #2.

Removes deprecated `tokio-core` and `domains` and use `tokio` and `trust-dns`.

I fully rewrote `happy_eyeballs.rs` so I hope nothing was broken. Echo client works. Echo component wasn't tested.

### CODE REVIEW

**Comment by astro** [comment]
Thank you very much!

**Comment by astro** [comment]
The updated dependencies affect the whole codebase and it builds just fine. Is there anything left to do for this?

**Comment by o01eg** [comment]
No, I've forgot to remove `[WIP]` from title. I think it finished but I suppose it better to test `echo_component`.

**Comment by astro** [comment]
Component connections don't work. Still looking into that…

**Pull request merged**
